### ISSUE TITLE
Consider adding an aligned repeat function for easier mirroring of LaTeX outline styles

### ISSUE THREAD

**Issue by ensko** [RubixDev/typst-outrageous#2]
LaTeX outlines are often (by default?) styled in such a way that the filling dots are aligned: all dots are spaced in such a way that a series of vertical lines goes through all of them, with a fixed distance between them. Typst's `repeat` function instead spaces according to the available space and can thus have different spacing for different lines.

There is [a function by EpicEricEE](https://github.com/EpicEricEE/typst-plugins/blob/b13b0e1bc30beba65ff19d029e2dad61239a2819/outex/src/outex.typ#L1-L27) that implements fixed spacing that can be used to fix this. The function is available under the MIT license, which is compatible with GPLv3. Adding it (and maybe using it by default) would imo improve this library a lot and make it even more a go-to solution for people looking to style their outlines like LaTeX.

If you agree, and help me make sure the code is incorporated properly regarding licensing, I could add this in a PR. Right now, I'm using that function in a template like this:
```typ
show outline.entry: outrageous.show-entry.with(
  fill: (none, box(width: 1fr, align(right, utils.repeat(gap: 3pt)[.]))),
)
```
A more canonical way to integrate this would probably be to provide a `repeat` parameter that lets you choose between the built-in one and the fixed-distance one; something like this:
```typ
show outline.entry: outrageous.show-entry.with(
  repeat: (auto, 3pt),
  fill: (none, [.]),
)
```
I'd be interested to hear what you think!

**Comment by RubixDev** [comment]
I will submit v0.2.0 for publishing soon. There you'll simply find that custom `repeat` function exported by `outrageous` so you can use it with `align(right, outrageous.repeat(gap: 6pt)[.])` or similar. The outrageous presets also switched to using that repeat function.
