### ISSUE TITLE
Upgrade to use `context` expressions

### ISSUE THREAD

**Issue by aaron-jack-manning** [RubixDev/typst-outrageous#3]
Many features of Typst used by this library (`locate` with a callback, `measure` with a styles argument, etc) are deprecated in the 0.12.0 release candidate in favor of [context expressions](https://typst.app/docs/reference/context/) and thus produce warnings in 0.12.0. Since context expressions were introduced as the preferred alternative in 0.11.0, it would make sense to upgrade before the main 0.12.0 release for a seamless transition.

I am happy to make a PR and do this, I just wanted confirmation/agreement beforehand.

**Comment by aaron-jack-manning** [comment]
I created a PR anyway because I made the edit for myself locally. Feel free to edit or close if there is disagreement about the changes.

**Comment by RubixDev** [comment]
Thanks! I only recently noticed that context expressions are a thing already, and had in mind that i'd need to update this package soon.
